image: node:9.11

pipelines:
  default:
    - step:
        script:
          - yarn
          - yarn lint:fix
          - yarn test

  master:
    - step:
        script:
          - yarn
          - yarn lint:fix
          - yarn test
          - yarn deploy-function
