image: node:9.11

pipelines:
  branches:
    master:
      - step:
          script:
            - yarn
            - yarn lint:fix
            - yarn test
            - yarn deploy-function


    custom:
      - step:
          script:
            - yarn
            - yarn lint:fix
            - yarn test

