image: node:9.11

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - yarn
            - yarn lint:fix
            - yarn test
            - yarn deploy-function
