image: node:latest

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - yarn --ignore-engines
            - yarn lint:fix
            - yarn test
            - yarn deploy-function
