image: node:10.15.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - yarn
            - yarn lint:fix
            - yarn test
            - yarn deploy-function
