image: node:9.11

pipelines:
  default:
    - step:
        script:
          - yarn
          - yarn lint:fix
          - yarn test

   branches:
      master:
        - step:
            script:
              - yarn deploy-function


